services:

  ################################
  # MongoDB
  ################################

  mongo:
    image: mongo:8
    container_name: overleaf-mongo
    restart: always
    command: ["mongod","--bind_ip_all","--replSet","overleaf"]

    volumes:
      - /opt/overleaf/mongo_data:/data/db

    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10


  ################################
  # Mongo replica init
  ################################

  mongo-init-replica:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"

    entrypoint: >
      bash -c "
      mongosh --host mongo:27017 --eval '
      rs.initiate({
        _id:\"overleaf\",
        members:[{_id:0,host:\"mongo:27017\"}]
      })' || true
      "


  ################################
  # Redis
  ################################

  redis:
    image: redis:7
    container_name: overleaf-redis
    restart: always

    command: ["redis-server","--appendonly","yes"]

    volumes:
      - /opt/overleaf/redis_data:/data


  ################################
  # Overleaf
  ################################

  sharelatex:
    build: .
    image: overleaf-full
    container_name: overleaf
    restart: always

    depends_on:
      - mongo
      - redis
      - mongo-init-replica

    ports:
      - "80:80"

    volumes:
      - /opt/overleaf/sharelatex_data:/var/lib/overleaf

    environment:

      ################################
      # APP
      ################################

      OVERLEAF_APP_NAME: "Overleaf CE"
      OVERLEAF_SITE_URL: "http://localhost"
      OVERLEAF_NAV_TITLE: "Overleaf"

      ################################
      # DATABASE
      ################################

      OVERLEAF_MONGO_URL: mongodb://mongo:27017/sharelatex?replicaSet=overleaf

      ################################
      # REDIS
      ################################

      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis

      ################################
      # FEATURES
      ################################

      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"

      ################################
      # FILE TYPES
      ################################

      ENABLED_LINKED_FILE_TYPES: project_file,project_output_file

      ################################
      # TEX CACHE
      ################################

      TEXMFVAR: /var/lib/overleaf/tmp/texmf-var


  ################################
  # Admin auto creation
  ################################

  admin-init:
    image: docker:cli
    depends_on:
      - sharelatex
    restart: "no"

    environment:
      OVERLEAF_ADMIN_EMAIL: ${OVERLEAF_ADMIN_EMAIL}
      OVERLEAF_ADMIN_PASSWORD: ${OVERLEAF_ADMIN_PASSWORD}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-admin.sh:/init-admin.sh

    entrypoint: ["sh","/init-admin.sh"]