services:
  openvscode:
    build: .
    container_name: openvscode
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./workspace:/home/workspace
      - ./extensions:/home/openvscode-server/.openvscode-server/extensions
      - ./user-data:/home/openvscode-server/.openvscode-server/data

    environment:
      - OPENVSCODE_SERVER_PORT=3000

    command: >
      openvscode-server
      --host 0.0.0.0
      --port 3000
      --without-connection-token
