FROM alpine:3.20

RUN apk add --no-cache docker-cli curl ca-certificates && \
    curl -sSL https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc && \
    chmod +x /usr/local/bin/mc

ENTRYPOINT ["/bin/sh"]
